{% set name = "versionfinder" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 157ad93efccf8f91ab094442526ea794f11c46d582cc6cd7a76dcfba20c805e6

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - gitpython ~=3.1
    - python >={{ python_min }}

test:
  imports:
    - versionfinder
    - versionfinder.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jantman/versionfinder
  summary: Python package to find the version of another package, whether installed via pip, setuptools or git.
  license: LGPL-3.0-only
  license_file: LICENSE
  doc_url: https://versionfinder.readthedocs.io
  dev_url: https://github.com/jantman/versionfinder

extra:
  recipe-maintainers:
    - BastianZim
    - jantman
